version: '3'
services:
  web:
    image: nginx
    #из локального копирует в гостевую
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - php-fpm
      - db
  php-fpm:
    build: docker/php
    restart: always
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - .:/var/www/html
    env_file:
      - .env

  db:
    image: postgres:13.1
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./sourcefiles/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"